[package]
name = "binimage"
version = "0.1.2"
authors = ["teaearlgraycold <supacoofoo@gmail.com>"]
repository = "https://github.com/teaearlgraycold/binimage"
license = "MIT"

[dependencies]
image = "*"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "binimage"
doc = false
test = false
